//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntTVapi.EntityDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BLOG()
        {
            this.BLOGCOMMENTs = new HashSet<BLOGCOMMENT>();
        }
    
        public int blogId { get; set; }
        public string blogCategory { get; set; }
        public string blogName { get; set; }
        public string blogPublisher { get; set; }
        public string blogContent { get; set; }
        public System.DateTime blogDate { get; set; }
        public string blogMainPictureLink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BLOGCOMMENT> BLOGCOMMENTs { get; set; }
    }
}
