//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntTVapi.EntityDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOGCOMMENT
    {
        public int commentId { get; set; }
        public int blogId { get; set; }
        public string commentContent { get; set; }
    
        public virtual BLOG BLOG { get; set; }
    }
}
