//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntTVapi.EntityDataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Data.Entity.Validation;
    using System.Diagnostics;

    public partial class tvcoilEntities : DbContext
    {
        public tvcoilEntities() : base("name=tvcoilEntities")
        {
        }

		public override int SaveChanges()
		{
			try
			{
				return base.SaveChanges();
			}
			catch (DbEntityValidationException ex)
			{
				// Retrieve the error messages as a list of strings.
				var errorMessages = ex.EntityValidationErrors
						.SelectMany(x => x.ValidationErrors)
						.Select(x => x.ErrorMessage);

				// Join the list to a single string.
				var fullErrorMessage = string.Join("; ", errorMessages);
				Debug.WriteLine("DbEntityValidationException: " + errorMessages);
				throw new DbEntityValidationException(fullErrorMessage, ex.EntityValidationErrors);
			}
		}

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BLOG> BLOGs { get; set; }
        public virtual DbSet<BLOGCOMMENT> BLOGCOMMENTs { get; set; }
        public virtual DbSet<NEWS> NEWS { get; set; }
        public virtual DbSet<PROGRAM> PROGRAMs { get; set; }
        public virtual DbSet<TRANSLATION> TRANSLATIONs { get; set; }
    
        public virtual int DeleteBlog(Nullable<int> blogId)
        {
            var blogIdParameter = blogId.HasValue ?
                new ObjectParameter("blogId", blogId) :
                new ObjectParameter("blogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteBlog", blogIdParameter);
        }
    
        public virtual int DeleteBlogComment(Nullable<int> commentId)
        {
            var commentIdParameter = commentId.HasValue ?
                new ObjectParameter("commentId", commentId) :
                new ObjectParameter("commentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteBlogComment", commentIdParameter);
        }
    
        public virtual int DeleteNews(Nullable<int> newsID)
        {
            var newsIDParameter = newsID.HasValue ?
                new ObjectParameter("newsID", newsID) :
                new ObjectParameter("newsID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteNews", newsIDParameter);
        }
    
        public virtual int DeleteProgram(Nullable<int> programID)
        {
            var programIDParameter = programID.HasValue ?
                new ObjectParameter("programID", programID) :
                new ObjectParameter("programID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProgram", programIDParameter);
        }
    
        public virtual int DeleteTranslation(string translationKey)
        {
            var translationKeyParameter = translationKey != null ?
                new ObjectParameter("translationKey", translationKey) :
                new ObjectParameter("translationKey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteTranslation", translationKeyParameter);
        }
    
        public virtual ObjectResult<GetAllBlog_Result> GetAllBlog()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllBlog_Result>("GetAllBlog");
        }
    
        public virtual ObjectResult<GetAllBlogComment_Result> GetAllBlogComment()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllBlogComment_Result>("GetAllBlogComment");
        }
    
        public virtual ObjectResult<GetAllNews_Result> GetAllNews()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllNews_Result>("GetAllNews");
        }
    
        public virtual ObjectResult<GetAllPrograms_Result> GetAllPrograms()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllPrograms_Result>("GetAllPrograms");
        }
    
        public virtual ObjectResult<GetAllTranslation_Result> GetAllTranslation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllTranslation_Result>("GetAllTranslation");
        }
    
        public virtual ObjectResult<GetBlogById_Result> GetBlogById(Nullable<int> blogId)
        {
            var blogIdParameter = blogId.HasValue ?
                new ObjectParameter("blogId", blogId) :
                new ObjectParameter("blogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBlogById_Result>("GetBlogById", blogIdParameter);
        }
    
        public virtual ObjectResult<GetBlogCommentById_Result> GetBlogCommentById(Nullable<int> commentId)
        {
            var commentIdParameter = commentId.HasValue ?
                new ObjectParameter("commentId", commentId) :
                new ObjectParameter("commentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBlogCommentById_Result>("GetBlogCommentById", commentIdParameter);
        }
    
        public virtual ObjectResult<GetBlogCommentsByBlogId_Result> GetBlogCommentsByBlogId(Nullable<int> blogId)
        {
            var blogIdParameter = blogId.HasValue ?
                new ObjectParameter("blogId", blogId) :
                new ObjectParameter("blogId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBlogCommentsByBlogId_Result>("GetBlogCommentsByBlogId", blogIdParameter);
        }
    
        public virtual ObjectResult<GetNewsById_Result> GetNewsById(Nullable<int> newsID)
        {
            var newsIDParameter = newsID.HasValue ?
                new ObjectParameter("newsID", newsID) :
                new ObjectParameter("newsID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNewsById_Result>("GetNewsById", newsIDParameter);
        }
    
        public virtual ObjectResult<GetProgramById_Result> GetProgramById(Nullable<int> programID)
        {
            var programIDParameter = programID.HasValue ?
                new ObjectParameter("programID", programID) :
                new ObjectParameter("programID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProgramById_Result>("GetProgramById", programIDParameter);
        }
    
        public virtual ObjectResult<GetTranslationByKey_Result> GetTranslationByKey(string translationKey)
        {
            var translationKeyParameter = translationKey != null ?
                new ObjectParameter("translationKey", translationKey) :
                new ObjectParameter("translationKey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTranslationByKey_Result>("GetTranslationByKey", translationKeyParameter);
        }
    
        public virtual ObjectResult<PostBlog_Result> PostBlog(string blogCategory, string blogName, string blogPublisher, string blogContent, Nullable<System.DateTime> blogDate, string blogMainPictureLink)
        {
            var blogCategoryParameter = blogCategory != null ?
                new ObjectParameter("blogCategory", blogCategory) :
                new ObjectParameter("blogCategory", typeof(string));
    
            var blogNameParameter = blogName != null ?
                new ObjectParameter("blogName", blogName) :
                new ObjectParameter("blogName", typeof(string));
    
            var blogPublisherParameter = blogPublisher != null ?
                new ObjectParameter("blogPublisher", blogPublisher) :
                new ObjectParameter("blogPublisher", typeof(string));
    
            var blogContentParameter = blogContent != null ?
                new ObjectParameter("blogContent", blogContent) :
                new ObjectParameter("blogContent", typeof(string));
    
            var blogDateParameter = blogDate.HasValue ?
                new ObjectParameter("blogDate", blogDate) :
                new ObjectParameter("blogDate", typeof(System.DateTime));
    
            var blogMainPictureLinkParameter = blogMainPictureLink != null ?
                new ObjectParameter("blogMainPictureLink", blogMainPictureLink) :
                new ObjectParameter("blogMainPictureLink", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PostBlog_Result>("PostBlog", blogCategoryParameter, blogNameParameter, blogPublisherParameter, blogContentParameter, blogDateParameter, blogMainPictureLinkParameter);
        }
    
        public virtual ObjectResult<PostBlogComment_Result> PostBlogComment(Nullable<int> blogId, string commentContent)
        {
            var blogIdParameter = blogId.HasValue ?
                new ObjectParameter("blogId", blogId) :
                new ObjectParameter("blogId", typeof(int));
    
            var commentContentParameter = commentContent != null ?
                new ObjectParameter("commentContent", commentContent) :
                new ObjectParameter("commentContent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PostBlogComment_Result>("PostBlogComment", blogIdParameter, commentContentParameter);
        }
    
        public virtual ObjectResult<PostNews_Result> PostNews(string newsCategory, string newsGenre, string newsName, string newsDescription, Nullable<System.DateTime> newsDateTime, string newsMainPictureLink, string newsVideoLink, Nullable<bool> newsPrefered)
        {
            var newsCategoryParameter = newsCategory != null ?
                new ObjectParameter("newsCategory", newsCategory) :
                new ObjectParameter("newsCategory", typeof(string));
    
            var newsGenreParameter = newsGenre != null ?
                new ObjectParameter("newsGenre", newsGenre) :
                new ObjectParameter("newsGenre", typeof(string));
    
            var newsNameParameter = newsName != null ?
                new ObjectParameter("newsName", newsName) :
                new ObjectParameter("newsName", typeof(string));
    
            var newsDescriptionParameter = newsDescription != null ?
                new ObjectParameter("newsDescription", newsDescription) :
                new ObjectParameter("newsDescription", typeof(string));
    
            var newsDateTimeParameter = newsDateTime.HasValue ?
                new ObjectParameter("newsDateTime", newsDateTime) :
                new ObjectParameter("newsDateTime", typeof(System.DateTime));
    
            var newsMainPictureLinkParameter = newsMainPictureLink != null ?
                new ObjectParameter("newsMainPictureLink", newsMainPictureLink) :
                new ObjectParameter("newsMainPictureLink", typeof(string));
    
            var newsVideoLinkParameter = newsVideoLink != null ?
                new ObjectParameter("newsVideoLink", newsVideoLink) :
                new ObjectParameter("newsVideoLink", typeof(string));
    
            var newsPreferedParameter = newsPrefered.HasValue ?
                new ObjectParameter("newsPrefered", newsPrefered) :
                new ObjectParameter("newsPrefered", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PostNews_Result>("PostNews", newsCategoryParameter, newsGenreParameter, newsNameParameter, newsDescriptionParameter, newsDateTimeParameter, newsMainPictureLinkParameter, newsVideoLinkParameter, newsPreferedParameter);
        }
    
        public virtual ObjectResult<PostProgram_Result> PostProgram(string programCategory, string programGenre, string programName, string programDescription, Nullable<System.DateTime> programDateTime, string programMainPictureLink, string programVideoLink)
        {
            var programCategoryParameter = programCategory != null ?
                new ObjectParameter("programCategory", programCategory) :
                new ObjectParameter("programCategory", typeof(string));
    
            var programGenreParameter = programGenre != null ?
                new ObjectParameter("programGenre", programGenre) :
                new ObjectParameter("programGenre", typeof(string));
    
            var programNameParameter = programName != null ?
                new ObjectParameter("programName", programName) :
                new ObjectParameter("programName", typeof(string));
    
            var programDescriptionParameter = programDescription != null ?
                new ObjectParameter("programDescription", programDescription) :
                new ObjectParameter("programDescription", typeof(string));
    
            var programDateTimeParameter = programDateTime.HasValue ?
                new ObjectParameter("programDateTime", programDateTime) :
                new ObjectParameter("programDateTime", typeof(System.DateTime));
    
            var programMainPictureLinkParameter = programMainPictureLink != null ?
                new ObjectParameter("programMainPictureLink", programMainPictureLink) :
                new ObjectParameter("programMainPictureLink", typeof(string));
    
            var programVideoLinkParameter = programVideoLink != null ?
                new ObjectParameter("programVideoLink", programVideoLink) :
                new ObjectParameter("programVideoLink", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PostProgram_Result>("PostProgram", programCategoryParameter, programGenreParameter, programNameParameter, programDescriptionParameter, programDateTimeParameter, programMainPictureLinkParameter, programVideoLinkParameter);
        }
    
        public virtual ObjectResult<PostTranslation_Result> PostTranslation(string translationKey, string translationEnglish, string translationHebrew)
        {
            var translationKeyParameter = translationKey != null ?
                new ObjectParameter("translationKey", translationKey) :
                new ObjectParameter("translationKey", typeof(string));
    
            var translationEnglishParameter = translationEnglish != null ?
                new ObjectParameter("translationEnglish", translationEnglish) :
                new ObjectParameter("translationEnglish", typeof(string));
    
            var translationHebrewParameter = translationHebrew != null ?
                new ObjectParameter("translationHebrew", translationHebrew) :
                new ObjectParameter("translationHebrew", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PostTranslation_Result>("PostTranslation", translationKeyParameter, translationEnglishParameter, translationHebrewParameter);
        }
    
        public virtual ObjectResult<TopSixBlog_Result> TopSixBlog()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TopSixBlog_Result>("TopSixBlog");
        }
    
        public virtual ObjectResult<TopSixBlogComment_Result> TopSixBlogComment()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TopSixBlogComment_Result>("TopSixBlogComment");
        }
    
        public virtual ObjectResult<TopSixNews_Result> TopSixNews()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TopSixNews_Result>("TopSixNews");
        }
    
        public virtual ObjectResult<TopSixPrograms_Result> TopSixPrograms()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TopSixPrograms_Result>("TopSixPrograms");
        }
    
        public virtual ObjectResult<UpdateBlog_Result> UpdateBlog(Nullable<int> blogId, string blogCategory, string blogName, string blogPublisher, string blogContent, Nullable<System.DateTime> blogDate, string blogMainPictureLink)
        {
            var blogIdParameter = blogId.HasValue ?
                new ObjectParameter("blogId", blogId) :
                new ObjectParameter("blogId", typeof(int));
    
            var blogCategoryParameter = blogCategory != null ?
                new ObjectParameter("blogCategory", blogCategory) :
                new ObjectParameter("blogCategory", typeof(string));
    
            var blogNameParameter = blogName != null ?
                new ObjectParameter("blogName", blogName) :
                new ObjectParameter("blogName", typeof(string));
    
            var blogPublisherParameter = blogPublisher != null ?
                new ObjectParameter("blogPublisher", blogPublisher) :
                new ObjectParameter("blogPublisher", typeof(string));
    
            var blogContentParameter = blogContent != null ?
                new ObjectParameter("blogContent", blogContent) :
                new ObjectParameter("blogContent", typeof(string));
    
            var blogDateParameter = blogDate.HasValue ?
                new ObjectParameter("blogDate", blogDate) :
                new ObjectParameter("blogDate", typeof(System.DateTime));
    
            var blogMainPictureLinkParameter = blogMainPictureLink != null ?
                new ObjectParameter("blogMainPictureLink", blogMainPictureLink) :
                new ObjectParameter("blogMainPictureLink", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UpdateBlog_Result>("UpdateBlog", blogIdParameter, blogCategoryParameter, blogNameParameter, blogPublisherParameter, blogContentParameter, blogDateParameter, blogMainPictureLinkParameter);
        }
    
        public virtual ObjectResult<UpdateBlogComment_Result> UpdateBlogComment(Nullable<int> commentId, Nullable<int> blogId, string commentContent)
        {
            var commentIdParameter = commentId.HasValue ?
                new ObjectParameter("commentId", commentId) :
                new ObjectParameter("commentId", typeof(int));
    
            var blogIdParameter = blogId.HasValue ?
                new ObjectParameter("blogId", blogId) :
                new ObjectParameter("blogId", typeof(int));
    
            var commentContentParameter = commentContent != null ?
                new ObjectParameter("commentContent", commentContent) :
                new ObjectParameter("commentContent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UpdateBlogComment_Result>("UpdateBlogComment", commentIdParameter, blogIdParameter, commentContentParameter);
        }
    
        public virtual ObjectResult<UpdateNews_Result> UpdateNews(Nullable<int> newsID, string newsCategory, string newsGenre, string newsName, string newsDescription, Nullable<System.DateTime> newsDateTime, string newsMainPictureLink, string newsVideoLink, Nullable<bool> newsPrefered)
        {
            var newsIDParameter = newsID.HasValue ?
                new ObjectParameter("newsID", newsID) :
                new ObjectParameter("newsID", typeof(int));
    
            var newsCategoryParameter = newsCategory != null ?
                new ObjectParameter("newsCategory", newsCategory) :
                new ObjectParameter("newsCategory", typeof(string));
    
            var newsGenreParameter = newsGenre != null ?
                new ObjectParameter("newsGenre", newsGenre) :
                new ObjectParameter("newsGenre", typeof(string));
    
            var newsNameParameter = newsName != null ?
                new ObjectParameter("newsName", newsName) :
                new ObjectParameter("newsName", typeof(string));
    
            var newsDescriptionParameter = newsDescription != null ?
                new ObjectParameter("newsDescription", newsDescription) :
                new ObjectParameter("newsDescription", typeof(string));
    
            var newsDateTimeParameter = newsDateTime.HasValue ?
                new ObjectParameter("newsDateTime", newsDateTime) :
                new ObjectParameter("newsDateTime", typeof(System.DateTime));
    
            var newsMainPictureLinkParameter = newsMainPictureLink != null ?
                new ObjectParameter("newsMainPictureLink", newsMainPictureLink) :
                new ObjectParameter("newsMainPictureLink", typeof(string));
    
            var newsVideoLinkParameter = newsVideoLink != null ?
                new ObjectParameter("newsVideoLink", newsVideoLink) :
                new ObjectParameter("newsVideoLink", typeof(string));
    
            var newsPreferedParameter = newsPrefered.HasValue ?
                new ObjectParameter("newsPrefered", newsPrefered) :
                new ObjectParameter("newsPrefered", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UpdateNews_Result>("UpdateNews", newsIDParameter, newsCategoryParameter, newsGenreParameter, newsNameParameter, newsDescriptionParameter, newsDateTimeParameter, newsMainPictureLinkParameter, newsVideoLinkParameter, newsPreferedParameter);
        }
    
        public virtual ObjectResult<UpdateProgram_Result> UpdateProgram(Nullable<int> programID, string programCategory, string programGenre, string programName, string programDescription, Nullable<System.DateTime> programDateTime, string programMainPictureLink, string programVideoLink)
        {
            var programIDParameter = programID.HasValue ?
                new ObjectParameter("programID", programID) :
                new ObjectParameter("programID", typeof(int));
    
            var programCategoryParameter = programCategory != null ?
                new ObjectParameter("programCategory", programCategory) :
                new ObjectParameter("programCategory", typeof(string));
    
            var programGenreParameter = programGenre != null ?
                new ObjectParameter("programGenre", programGenre) :
                new ObjectParameter("programGenre", typeof(string));
    
            var programNameParameter = programName != null ?
                new ObjectParameter("programName", programName) :
                new ObjectParameter("programName", typeof(string));
    
            var programDescriptionParameter = programDescription != null ?
                new ObjectParameter("programDescription", programDescription) :
                new ObjectParameter("programDescription", typeof(string));
    
            var programDateTimeParameter = programDateTime.HasValue ?
                new ObjectParameter("programDateTime", programDateTime) :
                new ObjectParameter("programDateTime", typeof(System.DateTime));
    
            var programMainPictureLinkParameter = programMainPictureLink != null ?
                new ObjectParameter("programMainPictureLink", programMainPictureLink) :
                new ObjectParameter("programMainPictureLink", typeof(string));
    
            var programVideoLinkParameter = programVideoLink != null ?
                new ObjectParameter("programVideoLink", programVideoLink) :
                new ObjectParameter("programVideoLink", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UpdateProgram_Result>("UpdateProgram", programIDParameter, programCategoryParameter, programGenreParameter, programNameParameter, programDescriptionParameter, programDateTimeParameter, programMainPictureLinkParameter, programVideoLinkParameter);
        }
    
        public virtual ObjectResult<UpdateTranslation_Result> UpdateTranslation(string translationKey, string translationEnglish, string translationHebrew)
        {
            var translationKeyParameter = translationKey != null ?
                new ObjectParameter("translationKey", translationKey) :
                new ObjectParameter("translationKey", typeof(string));
    
            var translationEnglishParameter = translationEnglish != null ?
                new ObjectParameter("translationEnglish", translationEnglish) :
                new ObjectParameter("translationEnglish", typeof(string));
    
            var translationHebrewParameter = translationHebrew != null ?
                new ObjectParameter("translationHebrew", translationHebrew) :
                new ObjectParameter("translationHebrew", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UpdateTranslation_Result>("UpdateTranslation", translationKeyParameter, translationEnglishParameter, translationHebrewParameter);
        }
    }
}
