export enum ActionType{
    GetAllTranslations,
    GetTranslationByKey,

    GetAllBlogs,
    GetAllBlogsError,
    GetBlog,
    GetBlogError,
    AddBlog,
    AddBlogError,
    UpdateBlog,
    UpdateBlogError,
    DeleteBlog,
    DeleteBlogError,

    GetAllPrograms,
    GetAllProgramsError,
    GetProgram,
    GetProgramError,
    AddProgram,
    AddProgramError,
    UpdateProgram,
    UpdateProgramError,
    DeleteProgram,
    DeleteProgramError,

    GetAllBlogComments,
    GetAllBlogCommentsError,
    GetBlogComment,
    GetBlogCommentError,
    GetBlogCommentsByBlogId,
    GetBlogCommentsByBlogIdError,
    AddBlogComment,
    AddBlogCommentError,
    UpdateBlogComment,
    UpdateBlogCommentError,
    DeleteBlogComment,
    DeleteBlogCommentError,


    GetAllNews,
    GetAllNewsError,
    GetNews,
    GetNewsError,
    AddNews,
    AddNewsError,
    UpdateNews,
    UpdateNewsError,
    DeleteNews,
    DeleteNewsError
}